CREATE TABLE images
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name   VARCHAR(255),
    size        BIGINT                                  NOT NULL,
    upload_date TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT                                  NOT NULL,
    url         VARCHAR(255),
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE user_images
(
    user_id   BIGINT NOT NULL,
    image_url VARCHAR(255)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_images
    ADD CONSTRAINT fk_user_images_on_user FOREIGN KEY (user_id) REFERENCES users (id);