server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: phyllomedusatestmailsend@gmail.com
    password: upws xuvl tzid liwe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
