server:
  port: 8081

spring:
  application:
    name: mail-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}


kafka:
  topics:
    userWelcome: "user-welcome-topic"
    imageUpload: "image-upload-topic"
    imageDownload: "image-download-topic"

mail:
  host: smtp.gmail.com
  port: 587
  username: phyllomedusatestmailsend@gmail.com
  password: upws xuvl tzid liwe
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
